# SharpnessPro/__init__.py
from .HighPassSharpen import NODE_CLASS_MAPPINGS as HP_MAP, NODE_DISPLAY_NAME_MAPPINGS as HP_NAME
from .UnsharpMaskSharpen import NODE_CLASS_MAPPINGS as USM_MAP, NODE_DISPLAY_NAME_MAPPINGS as USM_NAME
from .SmartSharpen import NODE_CLASS_MAPPINGS as SS_MAP, NODE_DISPLAY_NAME_MAPPINGS as SS_NAME
from .Clarity import NODE_CLASS_MAPPINGS as CL_MAP, NODE_DISPLAY_NAME_MAPPINGS as CL_NAME
from .Texture import NODE_CLASS_MAPPINGS as TX_MAP, NODE_DISPLAY_NAME_MAPPINGS as TX_NAME

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(HP_MAP)
NODE_CLASS_MAPPINGS.update(USM_MAP)
NODE_CLASS_MAPPINGS.update(SS_MAP)
NODE_CLASS_MAPPINGS.update(CL_MAP)
NODE_CLASS_MAPPINGS.update(TX_MAP)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(HP_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(USM_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(SS_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(CL_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(TX_NAME)
